### ISSUE TITLE
n2t_hdl: Possible overlooking of edge case handling

### ISSUE THREAD

**Issue by vacuus** [zbrachinara/nand2tetris-rs#7]
Is the asymmetry of the `unwrap`ping intentional?
https://github.com/zbrachinara/nand2tetris-rs/blob/47113db80935766daddedddf8b275851379a1a6e/n2t_hdl/src/model/parser/interface.rs#L136-L150

**Comment by zbrachinara** [comment]
I'm going to be real with you, I pretty much forgot what all of this was supposed to do for a few minutes. I also somewhere along the line decided that doing it this way (having nodes as boxed chips and having multiple edges between nodes) was a horrible mistake, so I think I'll just be rewriting it all over again, this time not depending on petgraph.

As for whether or not the unwrapping is intentional, my best guess is no.

**Comment by vacuus** [comment]
Funny; it was just today that I started thinking about an implementation not using all the fancy graph stuff.
